POST http://localhost:3300/api/register HTTP/1.1
content-type: application/json

{
  "username": "ash",
  "password": "password"
}
###

POST http://localhost:3300/api/login HTTP/1.1
content-type: application/json

{
  "username": "ash",
  "password": "password"
}
###

GET http://localhost:3300/api/jokes HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTM2OTQzOTMwLCJleHAiOjE1MzY5NDc1MzB9.jReqhTK0QhHBMSiXml0TsK7Ha58dtTGVn0WB69dO1rg